name: Build and deploy app

on:
  push:
    branches:
      - churches
      - paintings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "docker_image=ghcr.io/netwerk-digitaal-erfgoed/heritageflix-${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Log in to Docker registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Build and push image to registry
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: |
            ${{ steps.vars.outputs.docker_image }}:${{ steps.vars.outputs.sha_short }}
            ${{ steps.vars.outputs.docker_image }}:latest

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Store DigitalOcean credentials
        run: doctl kubernetes cluster kubeconfig save nde

      - name: Update deployment
        run: |
          kubectl set image deployment/heritageflix-${GITHUB_REF_NAME} app=${{ steps.vars.outputs.docker_image }}:${{ steps.vars.outputs.sha_short }}
